version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run test:unit
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist